### ISSUE TITLE
Cordova 5.0.0 doesn't find the plugin in NPM

### ISSUE THREAD

**Issue by mrextreme** [gbenvenuti/cordova-plugin-screen-orientation#56]
`cordova plugin add cordova-plugin-screen-orientation`

gives me the result

```
Fetching plugin "cordova-plugin-screen-orientation" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-screen-orientation
npm http 404 https://registry.npmjs.org/cordova-plugin-screen-orientation
Fetching from npm failed: 404 Not Found: cordova-plugin-screen-orientation
Error: 404 Not Found: cordova-plugin-screen-orientation
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by gbenvenuti** [comment]
Sorry about that, typo in the npm package name, this has been fixed.
