### ISSUE TITLE
Error: 404 Not Found: cordova-plugin-screen-orientation at RegClient

### ISSUE THREAD

**Issue by markarupert** [gbenvenuti/cordova-plugin-screen-orientation#63]
Tried installing using: cordova plugin add cordova-plugin-screen-orientation

but I am getting the error below

Fetching plugin "cordova-plugin-screen-orientation" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-screen-orientation
npm http 404 http://registry.cordova.io/cordova-plugin-screen-orientation
Error: 404 Not Found: cordova-plugin-screen-orientation at RegClient.<anonymous> (C:\Users\Mark\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\request.js:268:14)
    at Request.self.callback (C:\Users\Mark\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Mark\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by gbenvenuti** [comment]
hi @markarupert 

What version of cordova are you using? If you're using > 4 then the command you typed should work, otherwise use
    
    cordova plugin add net.yoik.cordova.plugins.screenorientation

**Comment by markarupert** [comment]
I was able to install it with the yoik command line above.

Thanks!
